### ISSUE TITLE
config缺少参数

### ISSUE THREAD

**Issue by chicleee** [bbaibowen/EfficientDet_anchor_free#1]
您好！您的工作非常棒! 我尝试运行时报了下面错误
`Traceback (most recent call last):
  File "train.py", line 132, in <module>
    model = EfficientDet_Free(args)
  File "/home/kp/lx/EfficientDet_anchor_free/model/model.py", line 17, in __init__
    self.head = FCOSHead(config.out_channels, config.n_class, config.n_conv, config.prior)
AttributeError: 'Config' object has no attribute 'n_conv'
`

**Comment by chicleee** [comment]
另外configs里缺少一些参数呀

**Comment by bbaibowen** [comment]
> 您好！您的工作非常棒！我尝试运行时报了以下错误
> `Traceback (most recent call last): File "train.py", line 132, in <module> model = EfficientDet_Free(args) File "/home/kp/lx/EfficientDet_anchor_free/model/model.py", line 17, in __init__ self.head = FCOSHead(config.out_channels, config.n_class, config.n_conv, config.prior) AttributeError: 'Config' object has no attribute 'n_conv' `

你可以设置n_conv = 4，这是老的版本，等试验室开放后我会上传新的版本和权重

**Comment by bbaibowen** [comment]
> 另外configs里缺少一些参数呀

是的，缺少了n_conv，一般n_conv = 4，还有在保存参数的时候也有一些错误，把.module删除即可，等试验室开放后我会上传新的版本和权重

**Comment by bitwangdan** [comment]
> .module

hi，请问什么时候上传新的版本和权重呀？
